import { Mission, TrackId } from "./types";

export const tracks: { id: TrackId; label: string; description: string }[] = [
  { id: "frontend", label: "Frontend Engineer", description: "Interface quality, React architecture, performance, and accessibility." },
  { id: "backend", label: "Backend Foundations", description: "Node.js, APIs, data modelling, and reliable service behaviour." },
  { id: "fullstack", label: "Full-stack Delivery", description: "Own a product feature across UI, API, data, and operational trade-offs." },
  { id: "tester", label: "Quality Engineer", description: "Test strategy, automation, exploratory thinking, and release confidence." },
];

export const missions: Mission[] = [
  { id: "fe-state-tracing", track: "frontend", level: "Fresher", type: "diagnose", title: "Trace a broken UI state", summary: "Identify state ownership and explain why a familiar UI has become inconsistent.", prompt: "A product picker sometimes shows the wrong selected item after filtering. Explain how you would trace the state, identify ownership, and prevent stale derived state.", rubric: ["Separates source and derived state", "Names a reproducible debugging path", "Explains a durable fix"], xp: 40, prerequisites: [] },
  { id: "fe-semantic-form", track: "frontend", level: "Fresher", type: "build", title: "Build a resilient settings form", summary: "Ship a working HTML and JavaScript form that remains understandable through validation and failure.", prompt: "Use the in-app editor to build an account settings form with semantic HTML and vanilla JavaScript. Include client validation, an accessible error summary, focus management after a failed submit, and a pending save state. HTML and JavaScript are required; CSS is optional.", rubric: ["Includes working semantic controls and labels", "Handles client errors", "Moves focus to useful feedback", "Demonstrates a pending save state"], xp: 50, prerequisites: ["fe-state-tracing"] },
  { id: "fe-hydration-debug", track: "frontend", level: "Mid", type: "diagnose", title: "Debug a hydration mismatch", summary: "Find the server/client boundary that creates inconsistent React markup.", prompt: "A Next.js header reads localStorage while rendering and sometimes triggers a hydration mismatch. Explain the root cause, propose a safe fix, and list how you would verify it.", rubric: ["Explains server versus client rendering", "Avoids hiding the mismatch with suppressHydrationWarning", "Defines a concrete verification path"], xp: 80, prerequisites: ["fe-semantic-form"] },
  { id: "fe-accessible-filter", track: "frontend", level: "Mid", type: "build", title: "Build an accessible async filter", summary: "Implement an HTML and JavaScript filter that works with keyboard, screen reader, and slow APIs.", prompt: "Use the in-app editor to build a searchable project filter with vanilla JavaScript. Implement debouncing, loading/error/empty states, keyboard interaction, and protection from stale responses. HTML and JavaScript are required; CSS is optional.", rubric: ["Demonstrates clear state ownership", "Implements an accessible interaction model", "Prevents stale responses", "Covers loading and empty states"], xp: 100, prerequisites: ["fe-hydration-debug"] },
  { id: "fe-dashboard-design", track: "frontend", level: "Senior", type: "design", title: "Design a data-heavy dashboard", summary: "Make server/client, caching, and performance decisions for a complex UI.", prompt: "A security dashboard contains a table, filters, detail drawer, live status, and saved views. Write a short design proposal: questions, data boundaries, loading strategy, cache strategy, accessibility, observability, and trade-offs.", rubric: ["Makes assumptions explicit", "Explains server/client boundaries", "Considers performance and accessibility", "Names risks and observability"], xp: 160, prerequisites: ["fe-accessible-filter"] },
  { id: "fe-incident-recovery", track: "frontend", level: "Expert", type: "review", title: "Recover a slow release", summary: "Make an evidence-led recovery plan for a production frontend regression.", prompt: "A release has doubled interaction latency and increased checkout errors. Define your triage, rollback criteria, telemetry, ownership, customer communication, and prevention plan.", rubric: ["Prioritises user impact", "Defines measurable rollback criteria", "Balances speed and learning"], xp: 240, prerequisites: ["fe-dashboard-design"] },
  { id: "be-error-contract", track: "backend", level: "Fresher", type: "diagnose", title: "Define a dependable API error contract", summary: "Make server validation failures useful without leaking implementation details.", prompt: "A Node.js create-order endpoint currently returns raw exceptions. Define the request-validation flow, stable JSON error contract, HTTP status choices, structured logging, and how a client should recover from validation versus unexpected failures.", rubric: ["Separates client and server failures", "Defines a stable API contract", "Protects sensitive detail", "Explains client recovery"], xp: 50, prerequisites: [] },
  { id: "be-indexed-pagination", track: "backend", level: "Mid", type: "design", title: "Paginate a growing API", summary: "Choose pagination and indexing that remain correct as data grows.", prompt: "Design an orders endpoint for a table with millions of rows. Compare offset and cursor pagination, define a cursor, indexes, consistency trade-offs, and tests.", rubric: ["Selects an appropriate pagination model", "Connects indexes to access patterns", "Covers changing data"], xp: 100, prerequisites: ["be-error-contract"] },
  { id: "be-xp-idempotency", track: "backend", level: "Mid", type: "diagnose", title: "Prevent duplicate XP awards", summary: "Fix a race condition in a mission-completion API.", prompt: "Two browser tabs submit the same completed mission at once, awarding XP twice. Describe a NestJS/PostgreSQL solution, including schema constraints, transaction boundaries, API response, and tests.", rubric: ["Uses database-enforced idempotency", "Explains transaction behaviour", "Covers concurrent tests", "Considers auditability"], xp: 120, prerequisites: ["be-indexed-pagination"] },
  { id: "be-outbox-retries", track: "backend", level: "Senior", type: "design", title: "Ship reliable side effects", summary: "Prevent a successful write from losing its downstream work.", prompt: "An order must charge a card and notify fulfilment. Design an outbox and retry system with idempotency, observability, failure handling, and operational ownership.", rubric: ["Defines transaction boundaries", "Handles at-least-once delivery", "Includes operational signals"], xp: 170, prerequisites: ["be-xp-idempotency"] },
  { id: "be-threat-model", track: "backend", level: "Expert", type: "review", title: "Threat-model an account API", summary: "Find high-value abuse paths before a public launch.", prompt: "Review an account API handling login links, profile updates, and exports. Identify threats, trust boundaries, mitigations, abuse monitoring, and residual risk.", rubric: ["Identifies realistic attack paths", "Prioritises mitigations", "Includes detection and response"], xp: 240, prerequisites: ["be-outbox-retries"] },
  { id: "fs-feature-slice", track: "fullstack", level: "Fresher", type: "design", title: "Plan a small feature slice", summary: "Break a user need into a UI, API, data, and verification path.", prompt: "Plan a saved-search feature from user interaction through persistence. Define the smallest vertical slice, interfaces, failure states, and acceptance criteria.", rubric: ["Connects all layers", "Keeps scope small", "Defines verification"], xp: 60, prerequisites: [] },
  { id: "fs-resilient-submit", track: "fullstack", level: "Mid", type: "build", title: "Build a resilient submission flow", summary: "Implement a browser submission flow that survives retries and partial failures.", prompt: "Use the in-app editor to build a feedback submission flow with duplicate prevention, retry behaviour, accessible status updates, and a simulated failure/recovery path. HTML and JavaScript are required; CSS is optional.", rubric: ["Shows clear UI state transitions", "Prevents duplicate submissions", "Recovers from failure", "Uses accessible status updates"], xp: 120, prerequisites: ["fs-feature-slice"] },
  { id: "fs-mission-contract", track: "fullstack", level: "Senior", type: "design", title: "Ship mission completion end-to-end", summary: "Define a robust contract from interaction to persisted progress.", prompt: "Design the UI, API, database write, failure behaviour, retry strategy, and analytics for completing a mission. Include optimistic update trade-offs and how you prevent progress loss.", rubric: ["Connects UI and API contract", "Handles retry and failure", "Protects data integrity", "Explains observability"], xp: 180, prerequisites: ["fs-resilient-submit", "fe-dashboard-design", "be-xp-idempotency"] },
  { id: "fs-rollout-rollback", track: "fullstack", level: "Expert", type: "review", title: "Lead a safe production rollout", summary: "Turn a risky feature launch into an observable, reversible delivery plan.", prompt: "Prepare a rollout and rollback plan for a schema-changing feature. Cover migration compatibility, flags, telemetry, ownership, communication, and post-launch review.", rubric: ["Keeps deployment reversible", "Defines decision signals", "Coordinates technical and human response"], xp: 260, prerequisites: ["fs-mission-contract"] },
  { id: "qa-risk-based-testing", track: "tester", level: "Fresher", type: "diagnose", title: "Find the highest-risk paths", summary: "Turn a feature brief into a focused, high-value test plan.", prompt: "A checkout feature adds discount codes, guest checkout, and payment retries. Identify the highest-risk user journeys, explain the risks, and choose the first tests you would run.", rubric: ["Prioritises by user and business risk", "Covers happy paths and failure paths", "Explains test choices"], xp: 50, prerequisites: [] },
  { id: "qa-validation-harness", track: "tester", level: "Mid", type: "build", title: "Build a validation test harness", summary: "Use HTML and JavaScript to exercise a form’s essential validation behavior.", prompt: "Use the in-app editor to build a small form and a test-harness panel. Exercise required fields, invalid email, valid submission, and reset behavior. Show each test as pass or fail. HTML and JavaScript are required; CSS is optional.", rubric: ["Covers meaningful validation cases", "Reports pass and fail clearly", "Keeps tests repeatable", "Uses accessible status text"], xp: 120, prerequisites: ["qa-risk-based-testing"] },
  { id: "qa-test-strategy", track: "tester", level: "Senior", type: "design", title: "Design a release confidence strategy", summary: "Balance automation, exploratory testing, and observability for a risky release.", prompt: "A team is shipping account deletion across web and API. Define layered test coverage, exploratory sessions, test data, release gates, monitoring, and the risks that remain after release.", rubric: ["Uses appropriate test layers", "Includes exploratory testing", "Defines observable release gates", "Names residual risk"], xp: 190, prerequisites: ["qa-validation-harness"] },
  { id: "qa-regression-review", track: "tester", level: "Expert", type: "review", title: "Lead a regression incident review", summary: "Turn a production escape into lasting quality improvements.", prompt: "A regression deleted customer preferences during a migration. Review the incident: identify missed controls, improve test strategy and release process, define ownership, and measure whether the fix works.", rubric: ["Connects root cause to prevention", "Improves technical and process controls", "Defines measurable follow-through"], xp: 260, prerequisites: ["qa-test-strategy"] },
];
