import { Mission } from "./types";

const base = { track: "frontend" as const, level: "Fresher" as const, type: "build" as const, collection: "foundations" as const };

export const webFoundationMissions: Mission[] = [
  { ...base, id: "wf-semantic-profile", title: "Create a semantic profile page", summary: "Learn the landmarks that make a page easy to navigate.", prompt: "Build a short profile page. Use a main landmark, one clear page heading, and an image with useful alternative text.", rubric: ["Uses meaningful HTML landmarks", "Has one clear page heading", "Provides useful image alternative text"], xp: 25, prerequisites: [], lesson: { number: 1, concept: "Semantic HTML gives people and tools a clear map of your page.", hints: ["Start with <main> and <h1>.", "Use <section> when a group needs its own heading.", "Describe what an image communicates, not its file name."] } },
  { ...base, id: "wf-responsive-card", title: "Style a responsive card", summary: "Use CSS layout and focus states to make a small component feel intentional.", prompt: "Create a profile or project card with a heading, description, and action. Use Grid, Flexbox, or a media query, then make the keyboard focus state easy to see.", rubric: ["Uses responsive layout CSS", "Keeps content readable", "Shows a visible keyboard focus state"], xp: 30, prerequisites: ["wf-semantic-profile"], lesson: { number: 2, concept: "Responsive layout starts with flexible rules, not separate pages for every screen.", hints: ["Start with display: grid or display: flex.", "Use gap to create breathing room.", "Try :focus-visible on your action." ] } },
  { ...base, id: "wf-accessible-form", title: "Build an accessible contact form", summary: "Connect labels, controls, and helpful status feedback.", prompt: "Build a contact form with name, email, and message fields. Every field needs a connected label. Add a submit button and a live status message for feedback.", rubric: ["Connects each label to a field", "Uses an actual form", "Communicates status accessibly"], xp: 35, prerequisites: ["wf-responsive-card"], lesson: { number: 3, concept: "Forms work best when every person can understand what to enter and what happened next.", hints: ["Match label for with the input id.", "Use type=email for email addresses.", "Create an empty element with role=status for feedback." ] } },
  { ...base, id: "wf-theme-toggle", title: "Add a theme toggle", summary: "Use JavaScript events to change a visible state.", prompt: "Create a button that changes the page between two visual themes. Listen for clicks and toggle a class or data attribute on the page.", rubric: ["Uses a clearly named button", "Handles a click event", "Changes visual state without reloading"], xp: 35, prerequisites: ["wf-accessible-form"], lesson: { number: 4, concept: "An event listener lets your page respond when someone interacts with it.", hints: ["Select the button with document.querySelector.", "Use addEventListener('click', …).", "Toggle a class on document.body." ] } },
  { ...base, id: "wf-task-list", title: "Build a tiny task list", summary: "Turn input into visible DOM content.", prompt: "Build a task input with an Add button and a list. When someone adds a task, create a new list item and add it to the page.", rubric: ["Has an input and add button", "Uses a semantic list", "Creates list items with JavaScript"], xp: 40, prerequisites: ["wf-theme-toggle"], lesson: { number: 5, concept: "The DOM is the live document your JavaScript can read and change.", hints: ["Read the input value.", "Create an li with document.createElement.", "Append it to your ul, then clear the input." ] } },
  { ...base, id: "wf-mini-project", title: "Ship a small study planner", summary: "Combine structure, accessibility, styling, and interaction in one mini-project.", prompt: "Build a simple study planner. Structure it with header and main landmarks, include a labeled form, and add one JavaScript interaction that updates the page.", rubric: ["Uses semantic structure", "Includes a labeled form", "Includes a useful JavaScript interaction"], xp: 60, prerequisites: ["wf-task-list"], lesson: { number: 6, concept: "A small project is a chance to connect the skills you have practised one at a time.", hints: ["Reuse patterns from the earlier lessons.", "Build the HTML before the interaction.", "Test once with only your keyboard." ] } },
];
